<script runat="server" language="vbscript" type="text/vbscript">

	Const ADDNEW_RECORD = "0"
	Const UPDATE_RECORD = "1"
	Const DELETE_RECORD = "2"
	Const CONFIRM_ADDNEW = "3"
	Const CONFIRM_UPDATE = "4"
	Const CONFIRM_DELETE = "5"
	Const SHOW_DETAILS = "13"

	Const UPDATE_PASSWORD = "6"
	Const QUICK_ADD_MEMBER = "7"

	Const UPDATE_EVENTS = "10"
	Const UPDATE_SKILLS = "11"
	Const UPDATE_MEMBER_AVAILABILITY = "12"
	
	Const SHOW_HELP = "1"
	Const HIDE_HELP = "0"

	Const IS_POSTBACK = "1"
	Const IS_ENABLED = "1"
	Const IS_ACTIVE = "1"
	Const IS_NOT_SENT = "0"
	Const IS_SENT = "1"

	Const LOGOFF_USER = "50"
	Const LOGON_USER = "51"
	Const GET_LOGON_CREDENTIALS = "52"
	Const LOGOFF_SESSION_TIMEOUT = "53"
	Const LOGOFF_SESSION_ABANDON = "54"

	Const SEND_MESSAGE = "40"
	Const ADD_ATTACHMENT = "41"
	Const VIEW_EMAIL_GROUPS = "42"
	Const VIEW_EMAIL_MESSAGE = "43"
	Const DELETE_EMAIL_BULK = "44"
	Const FINISH_ATTACHMENT = "45"
	Const ADD_RECIPIENTS = "46"
	
	Const TYPE_EMAIL_RECIPIENTS	= "250"
	Const TYPE_CC_RECIPIENTS = "251"
	Const TYPE_BCC_RECIPIENTS = "252"
	
	Const RESEND_EMAIL_MESSAGE = "48"
	Const DISPLAY_ADDRESS_BOOK = "49"
	Const UPDATE_EMAIL_GROUPS_FOR_MESSAGE = "47"
		
	Const ADD_EMAIL_GROUP = "170"
	Const DISPLAY_CUSTOM_EMAIL_GROUPS = "171"
	Const INSERT_EMAIL_GROUP_MEMBERS = "172"
	Const DELETE_EMAIL_GROUP_MEMBERS = "173"
	
	Const SHOW_EMAIL_GROUP_DETAILS = "174"
	Const COMMIT_ADDRESSBOOK_EDIT = "48"

	Const PUBLISH_SCHEDULE = "20"
	Const PUBLISH_PROGRAM = "29"
	Const UNPUBLISH_SCHEDULE= "21"
	Const PUBLISH_EVENT = "27"
	Const EMAIL_SCHEDULE_TO_MEMBERS = "22"
	Const SEND_SCHEDULE_BY_EMAIL = "26"
	Const TOGGLE_IS_VISIBLE = "25"
	Const DISPLAY_MASTER_SCHEDULE = "23"
	Const COPY_EVENT_TEAM_TO_EVENT = "24"
	Const CLEAR_EVENT_TEAM_FROM_EVENT = "28"
	
	Const SMART_GROUP_PROGRAM = "230"
	Const SMART_GROUP_SKILL_GROUP = "231"
	Const SMART_GROUP_SKILL_UNGROUPED = "232"
	Const SMART_GROUP_SKILL = "233"
	Const SMART_GROUP_SCHEDULE_TEAM = "234"
	Const SMART_GROUP_EVENT_TEAM = "235"
	Const SMART_GROUP_CUSTOM_GROUP = "236"
	Const SMART_GROUP_EVENT_AVAILABLE = "240"
	Const SMART_GROUP_EVENT_NOT_AVAILABLE = "241"
	Const SMART_GROUP_EVENT_AVAILABILITY_MISSING = "242"
	Const SMART_GROUP_SKILL_AVAILABILITY_MISSING = "243"
	Const SMART_GROUP_SCHEDULE_AVAILABILITY_MISSING = "239"
	Const SMART_GROUP_PROGRAM_AVAILABILITY_MISSING = "244"
	
	Const CONTEXT_EVENT_MANAGER	= "1"

	Const IS_PUBLISHED = 0
	Const IS_MARKED_FOR_PUBLISH = 1
	Const IS_MARKED_FOR_UNPUBLISH = 2
	
	Const SCHEDULE_IS_PUBLISHED = 0
	Const SCHEDULE_HAS_UNPUBLISHED_CHANGES = 1
	Const SCHEDULE_HAS_NO_SCHEDULE_INFORMATION = 2

	' /admin/programs.asp
	Const TOGGLE_PROGRAM_IS_ENABLED = "160"

	'/schedule/build.asp
	Const EDIT_SCHEDULE = "60"

	' /admin/members.asp
	Const REMOVE_CLIENT_MEMBER = "74"
	Const REMOVE_PROGRAM_MEMBER = "73"
	Const ADD_PROGRAM_MEMBER = "72"
	Const CONFIGURE_PROGRAM_MEMBERS ="79"
	Const TOGGLE_CLIENT_ACTIVE_STATUS = "75"
	Const TOGGLE_PROGRAM_ACTIVE_STATUS = "76"
	Const IMPERSONATE_MEMBER = "77"
	Const SEND_MEMBER_CREDENTIALS ="78"
	Const SHOW_MEMBER_DETAILS = "70"
	Const SHOW_PROGRAM_MEMBER_DETAILS = "71"
	
	Const BULK_REMOVE_CLIENT_MEMBERS = "201"
	Const INVITE_MEMBERS = "200"
	Const GOTO_MEMBER_PROFILE = "202"

	' /member/programs.asp
	Const TOGGLE_PROGRAM_MEMBER_IS_ACTIVE = "150"
	Const SHOW_AVAILABLE_PROGRAMS = "151"
	Const NOTIFICATION_DISMISS = "152"
	Const NOTIFICATION_UNDO_DISMISS = "153"
	Const DISPLAY_NOTIFICATION = "154"
	Const SHOW_PROGRAM_DETAILS = "155"
	Const SHOW_AVAILABLE_PROGRAM_DETAILS = "156"
	
	' /member/settings.asp
	Const UPDATE_MEMBER_HOME_PAGE = "220"

	' /admin/memberskills.asp
	Const CONFIGURE_SINGLE_MEMBER_SKILLS = "80"
	Const CONFIGURE_PROGRAM_MEMBER_SKILLS = "81"
	
	' /admin/skillgroups.asp
	Const ASSIGN_SKILLS_TO_GROUPS = "85"
	Const TOGGLE_SKILL_GROUP_IS_ENABLED = "82"
	Const SHOW_SKILL_GROUP_DETAILS = "86"
	
	' /admin/skills.asp
	Const ASSIGN_SKILLS_TO_MEMBERS= "87"
	Const TOGGLE_SKILL_IS_ENABLED = "88"
	Const SHOW_SKILL_DETAILS = "89"
	
	' /admin/importmember.asp
	Const DO_UPLOAD_MEMBERS ="200"
	Const TEST_UPLOAD_MEMBERS = "201"
	Const CANCEL_UPLOAD_MEMBERS = "202"
	Const SHOW_IMPORT_REPORT = "203"

	' /client/account.asp
	Const INSERT_CLIENT_SUBSCRIPTION = "210"
	Const UPDATE_CLIENT_SUBSCRIPTION = "211"
	Const UPDATE_CLIENT_CONTACT_INFO = "212"		
	Const DELETE_CLIENT_SUBSCRIPTION = "213"		' delete subscription ..
	Const CANCEL_CLIENT_SUBSCRIPTION = "214"		' member clicked cancel account ..
	Const CANCEL_CLIENT_ACCOUNT = "215"
	Const ACCEPT_PAYMENT = "216"
	Const CONFIRM_PAYMENT = "217"
	
	' /client/preferences.asp
	Const INSERT_SAMPLE_PROGRAM = "218"

	' /member/schedule.asp
	Const SHOW_EVENT_DETAILS = "110"		     ' drilldown single event from click on event link
	Const SHOW_DATE_DETAILS = "111"			 ' all events for date from click on calendar date
	Const SHOW_CALENDAR_LIST_VIEW = "112"	 ' events for month in list view
	Const SHOW_CALENDAR_MONTH_VIEW = "113"	 ' [DEFAULT] events for month in calendar view
	Const SHOW_MEMBER_EVENTS = "114"		     ' list view of events where member is scheduled
	Const SHOW_COMPLETE_SCHEDULE_VIEW = "115"
	Const EMAIL_SINGLE_EVENT_TO_MEMBER = "116"
	Const DOWNLOAD_EVENT_AS_ICAL_FILE = "117"
	Const RESET_EVENT_AVAILABILITY = "118"
	Const SHOW_SCHEDULE_DETAILS = "119"
	
	Const SET_MEMBER_TO_AVAILABLE = "260"
	Const SET_MEMBER_TO_NOT_AVAILABLE = "261"
	Const GET_AVAILABILITY_FORM = "262"

	Const STREAM_FILE_TO_BROWSER = "120"
	Const DISPLAY_PRINT_VIEW = "121"
	Const GET_PDF_FOR_EVENT = "121"
	Const GET_PDF_FOR_DATE = "122"
	Const GET_PDF_FOR_MEMBER_EVENTS = "123"
	Const GET_PDF_FOR_LIST_VIEW = "124"
	Const GET_PDF_FOR_CALENDAR_VIEW = "125"
	Const GET_PDF_FOR_COMPLETE_SCHEDULE_VIEW = "126"

	Const GENERATE_PDF_FOR_DOWNLOAD = "1"
	Const GOTO_FIRST = 0
	Const GOTO_LAST = 1

	Const FILTER_FOR_MY_EVENTS = "-1"
	Const FILTER_FOR_PROGRAM = "-2"
	Const FILTER_FOR_SHOW_ALL = "0"

	' /schedule/schedule.asp
	Const GET_EVENT_LIST_FOR_CLIENT = "130"
	Const GET_EVENT_LIST_FOR_PROGRAM = "131"
	Const GET_EVENT_LIST_FOR_SCHEDULE = "132"
	Const MANAGE_EVENTS = "133"
	Const DELETE_MULTIPLE_EVENTS = "134"

	' /schedule/schedule.asp and /admin/events.asp
	Const DUPLICATE_EVENT = "140"
	
	' /client/settings.asp
	Const SHOW_SIGNUP_HTML = "180"
	Const EDIT_MEMBER_REQUIRED_FIELDS = "181"
	Const RESET_MEMBER_REQUIRED_FIELDS = "182"
	Const SET_MEMBER_PROFILE_REVIEW = "183"
	
	' /admin/files.asp
	Const DELETE_FILES_BULK = "190"
	Const SHOW_FILE_DETAILS = "191"
	Const LINK_FILES_TO_EVENTS = "192"
	
	' /ajax/_event_team.asp
	Const RETURN_SCHEDULE_ITEM = "0"
	Const RETURN_EVENT_TEAM = "1"
	
	Const SCHEDULE_ITEM_TYPE_COPY_TO = "0"
	Const SCHEDULE_ITEM_TYPE_COPY_FROM = "1"
	Const SCHEDULE_ITEM_TYPE_DEFAULT = "3"
	Const SCHEDULE_ITEM_TYPE_EDITOR = "3"

	' application notifications (dbo.Notification, dbo.MemberNotification)
	Const NOTIFICATION_SHOW_TO_ALL					= 0
	Const NOTIFICATION_SHOW_TO_ADMIN					= 1
	Const NOTIFICATION_STATUS_UNREAD					= 0
	Const NOTIFICATION_STATUS_MARKED_FOR_DISMISS		= 1
	Const NOTIFICATION_STATUS_MARKED_FOR_DELETE		= 2

	Const MEMBER_AVAILABILITY_IS_CURRENT = 0
	Const MEMBER_AVAILABILITY_NEEDS_UPDATE = 1

	Const MEMBER_PROFILE_NOT_COMPLETE = 0
	Const MEMBER_PROFILE_COMPLETE = 1

	' error codes
	Const NO_PROGRAMS_FOR_CLIENT = -3

	Const NO_SCHEDULES_FOR_PROGRAM = -2
	Const NO_SKILLS_FOR_PROGRAM = -4
	Const NO_MEMBERS_FOR_PROGRAM = -5

	Const NO_EVENTS_FOR_SCHEDULE = -1
	
	Const DB_ERROR_DUPLICATE_MEMBER = -2
	Const DB_ERROR_DUPLICATE_PROGRAM_NAME = -2
	
	' access level
	Const PERMIT_ADMIN = 10
	Const PERMIT_LEADER = 20
	Const PERMIT_MEMBER = 30
	Const PERMIT_ALL = 40
	
	' country codes enum
	Const UNITED_STATES_COUNTRY_CODE = 1
	Const CANADA_COUNTRY_CODE = 2
	
	' program enroll status id
	Const PROGRAM_ENROLL_STATUS_DECLINED = 1
	Const PROGRAM_ENROLL_STATUS_PENDING = 2
	Const PROGRAM_ENROLL_STATUS_ACCEPTED = 3
	
	' program member is enabled
	Const PROGRAM_MEMBER_NOT_IS_ACTIVE = 0
	Const PROGRAM_MEMBER_IS_ACTIVE = 1
	
	' codes for getting email message count for member
	Const RETURN_ALL_MESSAGES		= 0
	Const RETURN_SENT_MESSAGES		= 1
	Const RETURN_UNSENT_MESSAGES	= 2
	
	' home page constants
	Const MEMBER_HOME_PAGE_ID = 0
	Const MEMBER_CALENDAR_PAGE_ID = 1
	Const MEMBER_PROGRAMS_PAGE_ID = 2
	Const ADMIN_HOME_PAGE_ID = 3
	Const ADMIN_SCHEDULES_PAGE_ID = 4
	Const ADMIN_PROGRAMS_PAGE_ID = 5
	Const ADMIN_EMAIL_PAGE_ID = 6
	
	' sorting
	Const SORT_BY_EVENTDATE = "0"
	Const SORT_BY_PROGRAM_NAME = "1"
	Const SORT_BY_SCHEDULENAME = "2"
	Const SORT_BY_NEW_OR_CHANGED = "3"
	Const SORT_BY_FILE_NAME = "4"
	Const SORT_BY_FILE_EXTENSION = "5"
	Const SORT_BY_FILE_SIZE = "6"
	Const SORT_BY_IS_PUBLIC = "13"
	
	Const SORT_BY_SKILLNAME = "7"
	Const SORT_BY_SKILLGROUP = "8"
	Const SORT_BY_IS_MEMBER_SKILL = "9"
	Const SORT_BY_SKILL_IS_ENABLED = "12"
	
	Const SORT_BY_IS_AVAILABLE = "10"
	Const SORT_BY_IS_SCHEDULED = "11"
	
	Const SORT_BY_NAME_ASCENDING = "14"
	Const SORT_BY_NAME_DESCENDING = "15"
	Const SORT_BY_EMAIL = "16"


</script>